name: MNIST Model Python

on:
  push:
    branches: [ main, master ]  # specify branches
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup dataset and dataloaders
      run: |
        python setup.py
    
    - name: Model Summary
      run: |
        python model.py
    
    - name: Running tests for model
      run: |
        python tests.py
    
    - name: Training Model 
      run: |
        python train.py
    
    - name: Utils file run
      run: |
        python utils.py

    - name: Check workflow status
      run: |
        echo "✅ Workflow completed"